/* Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_SYS_STOP(Statechart* handle);
static void enact_main_region_ReadI2C(Statechart* handle);
static void enact_main_region_DisplayData(Statechart* handle);
static void enseq_main_region_SYS_STOP_default(Statechart* handle);
static void enseq_main_region_ReadI2C_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region_SYS_STOP(Statechart* handle);
static void exseq_main_region_ReadI2C(Statechart* handle);
static void exseq_main_region_DisplayData(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! The reactions of state SYS_STOP. */
static sc_integer main_region_SYS_STOP_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state ReadI2C. */
static sc_integer main_region_ReadI2C_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state DisplayData. */
static sc_integer main_region_DisplayData_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);






static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_set_sample_no(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	{
	};
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_in_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_SYS_STOP :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SYS_STOP] == Statechart_main_region_SYS_STOP
			);
				break;
		case Statechart_main_region_ReadI2C :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_READI2C] == Statechart_main_region_ReadI2C
			);
				break;
		case Statechart_main_region_DisplayData :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAYDATA] == Statechart_main_region_DisplayData
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.ev_RTC_Alarm_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_SYS_STOP :
		{
			main_region_SYS_STOP_react(handle,-1);
			break;
		}
		case Statechart_main_region_ReadI2C :
		{
			main_region_ReadI2C_react(handle,-1);
			break;
		}
		case Statechart_main_region_DisplayData :
		{
			main_region_DisplayData_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			clear_in_events(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_ev_RTC_Alarm(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_ev_RTC_Alarm);
	run_cycle(handle);
}



sc_integer statechart_get_sample_no(const Statechart* handle)
{
	return handle->iface.sample_no;
}
void statechart_set_sample_no(Statechart* handle, sc_integer value)
{
	handle->iface.sample_no = value;
}



/* implementations of all internal functions */

/* Entry action for state 'SYS_STOP'. */
static void enact_main_region_SYS_STOP(Statechart* handle)
{
	/* Entry action for state 'SYS_STOP'. */
	statechart_goSleep(handle);
}

static void enact_main_region_ReadI2C(Statechart* handle)
{
	/* Entry action for state 'ReadI2C'. */
	statechart_readI2CSensor(handle);
	handle->completed = bool_true;
}

static void enact_main_region_DisplayData(Statechart* handle)
{
	/* Entry action for state 'DisplayData'. */
	statechart_processData(handle);
	statechart_displayInfo(handle);
	handle->completed = bool_true;
}

/* 'default' enter sequence for state SYS_STOP */
static void enseq_main_region_SYS_STOP_default(Statechart* handle)
{
	/* 'default' enter sequence for state SYS_STOP */
	enact_main_region_SYS_STOP(handle);
	handle->stateConfVector[0] = Statechart_main_region_SYS_STOP;
}

/* 'default' enter sequence for state ReadI2C */
static void enseq_main_region_ReadI2C_default(Statechart* handle)
{
	/* 'default' enter sequence for state ReadI2C */
	enact_main_region_ReadI2C(handle);
	handle->stateConfVector[0] = Statechart_main_region_ReadI2C;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state SYS_STOP */
static void exseq_main_region_SYS_STOP(Statechart* handle)
{
	/* Default exit sequence for state SYS_STOP */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state ReadI2C */
static void exseq_main_region_ReadI2C(Statechart* handle)
{
	/* Default exit sequence for state ReadI2C */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state DisplayData */
static void exseq_main_region_DisplayData(Statechart* handle)
{
	/* Default exit sequence for state DisplayData */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_SYS_STOP :
		{
			exseq_main_region_SYS_STOP(handle);
			break;
		}
		case Statechart_main_region_ReadI2C :
		{
			exseq_main_region_ReadI2C(handle);
			break;
		}
		case Statechart_main_region_DisplayData :
		{
			exseq_main_region_DisplayData(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_SYS_STOP_default(handle);
}


static sc_integer main_region_SYS_STOP_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SYS_STOP. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.ev_RTC_Alarm_raised == bool_true)
			{ 
				exseq_main_region_SYS_STOP(handle);
				enseq_main_region_ReadI2C_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_ReadI2C_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ReadI2C. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state ReadI2C */
		handle->stateConfVector[0] = Statechart_last_state;
		/* 'default' enter sequence for state DisplayData */
		enact_main_region_DisplayData(handle);
		handle->stateConfVector[0] = Statechart_main_region_DisplayData;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_DisplayData_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisplayData. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state DisplayData */
		handle->stateConfVector[0] = Statechart_last_state;
		/* 'default' enter sequence for state SYS_STOP */
		enact_main_region_SYS_STOP(handle);
		handle->stateConfVector[0] = Statechart_main_region_SYS_STOP;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_ev_RTC_Alarm:
		{
			handle->iface.ev_RTC_Alarm_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
